import { Movie } from "@utils/api/getMovies";

export const RowMockProps: Movie[] = [
  {
    adult: false,
    backdrop_path: "/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg",
    genre_ids: [16, 878, 28],
    id: 610150,
    original_language: "ja",
    original_title: "ドラゴンボール超 スーパーヒーロー",
    overview:
      "The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.",
    popularity: 5953.989,
    poster_path: "/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg",
    release_date: "2022-06-11",
    title: "Dragon Ball Super: Super Hero",
    video: false,
    vote_average: 8,
    vote_count: 1426,
  },
  {
    adult: false,
    backdrop_path: "/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
    genre_ids: [28, 12, 14],
    id: 616037,
    original_language: "en",
    original_title: "Thor: Love and Thunder",
    overview:
      "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
    popularity: 5471.218,
    poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    release_date: "2022-07-06",
    title: "Thor: Love and Thunder",
    video: false,
    vote_average: 6.8,
    vote_count: 2846,
  },
  {
    adult: false,
    backdrop_path: "/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg",
    genre_ids: [28, 18, 878],
    id: 629176,
    original_language: "en",
    original_title: "Samaritan",
    overview:
      "Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.",
    popularity: 5096.329,
    poster_path: "/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg",
    release_date: "2022-08-25",
    title: "Samaritan",
    video: false,
    vote_average: 7,
    vote_count: 877,
  },
  {
    adult: false,
    backdrop_path: "/rqgeBNWXas1yrAyXxwi9CahfScx.jpg",
    genre_ids: [53],
    id: 985939,
    original_language: "en",
    original_title: "Fall",
    overview:
      "For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights.",
    popularity: 6731.327,
    poster_path: "/9f5sIJEgvUpFv0ozfA6TurG4j22.jpg",
    release_date: "2022-08-11",
    title: "Fall",
    video: false,
    vote_average: 7.4,
    vote_count: 346,
  },
  {
    adult: false,
    backdrop_path: "/yaze6df9AMIA9oeDEbIZ4zOTRCJ.jpg",
    genre_ids: [28, 12, 14],
    id: 960700,
    original_language: "ja",
    original_title: "鋼の錬金術師 完結編 復讐者スカー",
    overview:
      "The Elric brothers meet their toughest opponent yet — a lone serial killer with a large scar on his forehead.",
    popularity: 3120.09,
    poster_path: "/c5OwwBNyJkwyroIOIJL9IiRjydR.jpg",
    release_date: "2022-05-20",
    title: "Fullmetal Alchemist the Revenge of Scar",
    video: false,
    vote_average: 7,
    vote_count: 70,
  },
  {
    adult: false,
    backdrop_path: "/xfNHRI2f5kHGvogxLd0C5sB90L7.jpg",
    genre_ids: [16, 28, 10751, 878, 35],
    id: 539681,
    original_language: "en",
    original_title: "DC League of Super-Pets",
    overview:
      "When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.",
    popularity: 2932.591,
    poster_path: "/r7XifzvtezNt31ypvsmb6Oqxw49.jpg",
    release_date: "2022-07-27",
    title: "DC League of Super-Pets",
    video: false,
    vote_average: 7.6,
    vote_count: 475,
  },
  {
    adult: false,
    backdrop_path: "/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg",
    genre_ids: [53, 28, 878],
    id: 766507,
    original_language: "en",
    original_title: "Prey",
    overview:
      "When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.",
    popularity: 2812.935,
    poster_path: "/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg",
    release_date: "2022-08-02",
    title: "Prey",
    video: false,
    vote_average: 8,
    vote_count: 3713,
  },
  {
    adult: false,
    backdrop_path: "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
    genre_ids: [16, 12, 35, 14],
    id: 438148,
    original_language: "en",
    original_title: "Minions: The Rise of Gru",
    overview:
      "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
    popularity: 2192.824,
    poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    release_date: "2022-06-29",
    title: "Minions: The Rise of Gru",
    video: false,
    vote_average: 7.7,
    vote_count: 1879,
  },
  {
    adult: false,
    backdrop_path: "/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
    genre_ids: [28, 18],
    id: 361743,
    original_language: "en",
    original_title: "Top Gun: Maverick",
    overview:
      "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
    popularity: 2064.679,
    poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    release_date: "2022-05-24",
    title: "Top Gun: Maverick",
    video: false,
    vote_average: 8.4,
    vote_count: 3579,
  },
  {
    adult: false,
    backdrop_path: "/rHzoz94bRfyfNLjiIB26Wt5KDHE.jpg",
    genre_ids: [28, 80, 35, 12],
    id: 773867,
    original_language: "ko",
    original_title: "서울대작전",
    overview:
      "Chasing speed, dreams and money, a team of drivers get involved in the slush fund investigation of a powerful figure during the 1988 Seoul Olympics.",
    popularity: 2500.45,
    poster_path: "/ffX0TL3uKerLXACkuZGWhAPMbAq.jpg",
    release_date: "2022-08-26",
    title: "Seoul Vibe",
    video: false,
    vote_average: 6.9,
    vote_count: 59,
  },
  {
    adult: false,
    backdrop_path: "/3PieOs1t6dPHWlgvX3XoqTIQLqN.jpg",
    genre_ids: [12, 28, 878],
    id: 507086,
    original_language: "en",
    original_title: "Jurassic World Dominion",
    overview:
      "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
    popularity: 2194.336,
    poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
    release_date: "2022-06-01",
    title: "Jurassic World Dominion",
    video: false,
    vote_average: 7.1,
    vote_count: 3259,
  },
  {
    adult: false,
    backdrop_path: "/xVbppM1xgbskOKgOuV8fbWBWHtt.jpg",
    genre_ids: [27, 9648, 878, 53],
    id: 762504,
    original_language: "en",
    original_title: "Nope",
    overview:
      "Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
    popularity: 1783.019,
    poster_path: "/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
    release_date: "2022-07-20",
    title: "Nope",
    video: false,
    vote_average: 7,
    vote_count: 1321,
  },
  {
    adult: false,
    backdrop_path: "/pkLegAR3G5T63B2Xz2ijbD1BAm8.jpg",
    genre_ids: [27, 53, 28, 12, 80, 9648, 18, 10752],
    id: 927341,
    original_language: "en",
    original_title: "Hunting Ava Bravo",
    overview:
      "Billionaire sportsman Buddy King unwinds by hunting human captives on his remote mountain estate. But his latest victim, Ava Bravo is no easy target.",
    popularity: 1712.803,
    poster_path: "/etc6HKBEhNySNnYU2nRgbSeIyoW.jpg",
    release_date: "2022-04-01",
    title: "Hunting Ava Bravo",
    video: false,
    vote_average: 6.5,
    vote_count: 47,
  },
  {
    adult: false,
    backdrop_path: "/i0Y0wP8H6SRgjr6QmuwbtQbS24D.jpg",
    genre_ids: [28, 18],
    id: 579974,
    original_language: "te",
    original_title: "రౌద్రం రణం రుధిరం",
    overview:
      "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
    popularity: 1834.274,
    poster_path: "/nEufeZlyAOLqO2brrs0yeF1lgXO.jpg",
    release_date: "2022-03-24",
    title: "RRR",
    video: false,
    vote_average: 7.9,
    vote_count: 315,
  },
  {
    adult: false,
    backdrop_path: "/t9K8ycUBCplWiICDOKRNRYcEH9e.jpg",
    genre_ids: [16, 28, 14],
    id: 810693,
    original_language: "ja",
    original_title: "劇場版 呪術廻戦 0",
    overview:
      "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",
    popularity: 2173.428,
    poster_path: "/3pTwMUEavTzVOh6yLN0aEwR7uSy.jpg",
    release_date: "2021-12-24",
    title: "Jujutsu Kaisen 0",
    video: false,
    vote_average: 7.7,
    vote_count: 268,
  },
  {
    adult: false,
    backdrop_path: "/eiBMu2noc6r1QZLfQlFhfVtbXeM.jpg",
    genre_ids: [28, 53, 9648],
    id: 997120,
    original_language: "en",
    original_title: "Sniper: Rogue Mission",
    overview:
      "When a crooked federal agent is involved in a human sex trafficking ring, Sniper and CIA Rookie Brandon Beckett goes rogue, teaming up with his former allies Homeland Security Agent Zero and assassin Lady Death to uncover the corrupt agent and take down the criminal organization.",
    popularity: 1474.143,
    poster_path: "/jSL5TqroJsDAIgBdELBwby1uhf1.jpg",
    release_date: "2022-08-15",
    title: "Sniper: Rogue Mission",
    video: false,
    vote_average: 6.8,
    vote_count: 54,
  },
  {
    adult: false,
    backdrop_path: "/rwgmDkIEv8VjAsWx25ottJrFvpO.jpg",
    genre_ids: [10749, 18],
    id: 744276,
    original_language: "en",
    original_title: "After Ever Happy",
    overview:
      "As a shocking truth about a couple's families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.",
    popularity: 1366.839,
    poster_path: "/6b7swg6DLqXCO3XUsMnv6RwDMW2.jpg",
    release_date: "2022-08-24",
    title: "After Ever Happy",
    video: false,
    vote_average: 6.5,
    vote_count: 48,
  },
  {
    adult: false,
    backdrop_path: "/mCAkUizRRIwKMOlne9CIoJ3utSc.jpg",
    genre_ids: [53, 10770, 28],
    id: 951368,
    original_language: "en",
    original_title: "Your Boyfriend Is Mine",
    overview:
      "Over the objection of his girlfriend, Ben agrees to take a job as the “live in” man servant to a wealthy businesswoman, Amanda, but quickly realizes he has made a deal with the devil, and has put himself and his girlfriend in mortal jeopardy",
    popularity: 1486.197,
    poster_path: "/2OOYNZLKjdX8Z5KNyz7zZnHmodJ.jpg",
    release_date: "2022-03-19",
    title: "Your Boyfriend Is Mine",
    video: false,
    vote_average: 6.3,
    vote_count: 20,
  },
  {
    adult: false,
    backdrop_path: "/1n7ZGr6WeDOW4rFiQKmFel8baWH.jpg",
    genre_ids: [53, 27],
    id: 760741,
    original_language: "en",
    original_title: "Beast",
    overview:
      "A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.",
    popularity: 1316.291,
    poster_path: "/iRV0IB5xQeOymuGGUBarTecQVAl.jpg",
    release_date: "2022-08-11",
    title: "Beast",
    video: false,
    vote_average: 6.9,
    vote_count: 160,
  },
  {
    adult: false,
    backdrop_path: "/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg",
    genre_ids: [27, 53],
    id: 756999,
    original_language: "en",
    original_title: "The Black Phone",
    overview:
      "Finney Blake, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.",
    popularity: 1561.882,
    poster_path: "/lr11mCT85T1JanlgjMuhs9nMht4.jpg",
    release_date: "2022-06-22",
    title: "The Black Phone",
    video: false,
    vote_average: 7.9,
    vote_count: 2404,
  },
];
